# to build image:
# > docker-compose build

# to run container (and keep atached to the container)
# > docker-compose up [<service_name>]

# to run container as a daemon
# > docker-compose up -d [<service_name>]
# to attach to daemon container
# > docker exec -it <container_id> bash

# to stop the started container
# > docker-compose stop [<service_name>]

# to stop and remove the started container
# > docker-compose down [<service_name>]

version: "3"
services:
  sec2sky_api:
    image: sec2sky_api
    #restart: always
    tty: true
    depends_on:
      - sec2sky_mosquitto
      - sec2sky_db
    build:
      context: ..
      dockerfile: docker_pro/DockerfileAPI
    ports:
      - $PORT:8080
    environment:
      - MOSQUITTO_HOST=sec2sky_mosquitto
  sec2sky_mosquitto:
    image: sec2sky_mosquitto
    #restart: always
    tty: true
    build:
      context: ..
      dockerfile: docker_pro/DockerfileMosquitto
    environment:
      - TEST_VAR=8080
  sec2sky_db:
    image: mysql:5
    volumes:
      - ./docker_pro/persistance:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sec2sky
      MYSQL_ROOT_PASSWORD: s3c2sky
      MYSQL_USER: sec2sky
      MYSQL_PASSWORD: s3c2sky
    ports:
        - 3306:3306
